# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pong.ui'
#
# Created: Tue Nov 19 18:33:46 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Pong(object):
    def setupUi(self, Pong):
        Pong.setObjectName(_fromUtf8("Pong"))
        Pong.resize(435, 275)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Pong)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Pong)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.line = QtGui.QFrame(Pong)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button_l = QtGui.QPushButton(Pong)
        self.button_l.setObjectName(_fromUtf8("button_l"))
        self.gridLayout.addWidget(self.button_l, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Pong)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Pong)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Pong)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.button_s = QtGui.QPushButton(Pong)
        self.button_s.setObjectName(_fromUtf8("button_s"))
        self.gridLayout.addWidget(self.button_s, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(Pong)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 5, 2, 1, 1)
        self.label_10 = QtGui.QLabel(Pong)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(Pong)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 3, 2, 1, 1)
        self.label_15 = QtGui.QLabel(Pong)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(Pong)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Pong)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(Pong)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Pong)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(Pong)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(Pong)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.button_a = QtGui.QPushButton(Pong)
        self.button_a.setObjectName(_fromUtf8("button_a"))
        self.gridLayout.addWidget(self.button_a, 1, 0, 1, 1)
        self.button_k = QtGui.QPushButton(Pong)
        self.button_k.setObjectName(_fromUtf8("button_k"))
        self.gridLayout.addWidget(self.button_k, 3, 0, 1, 1)
        self.button_r = QtGui.QPushButton(Pong)
        self.button_r.setObjectName(_fromUtf8("button_r"))
        self.gridLayout.addWidget(self.button_r, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Pong)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_13 = QtGui.QLabel(Pong)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_17 = QtGui.QLabel(Pong)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 2, 3, 1, 1)
        self.label_18 = QtGui.QLabel(Pong)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 3, 3, 1, 1)
        self.label_19 = QtGui.QLabel(Pong)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Pong)
        QtCore.QMetaObject.connectSlotsByName(Pong)

    def retranslateUi(self, Pong):
        Pong.setWindowTitle(_translate("Pong", "Form", None))
        self.label.setText(_translate("Pong", "Einführungstext", None))
        self.button_l.setText(_translate("Pong", "P2 Down", None))
        self.label_2.setText(_translate("Pong", "a", None))
        self.label_3.setText(_translate("Pong", "s", None))
        self.label_9.setText(_translate("Pong", "1", None))
        self.button_s.setText(_translate("Pong", "P1 Down", None))
        self.label_16.setText(_translate("Pong", "5", None))
        self.label_10.setText(_translate("Pong", "Keyboard", None))
        self.label_14.setText(_translate("Pong", "3", None))
        self.label_15.setText(_translate("Pong", "4", None))
        self.label_5.setText(_translate("Pong", "k", None))
        self.label_6.setText(_translate("Pong", "l", None))
        self.label_11.setText(_translate("Pong", "Action", None))
        self.label_7.setText(_translate("Pong", "r", None))
        self.label_8.setText(_translate("Pong", "0", None))
        self.label_12.setText(_translate("Pong", "Multi Touch Electrode", None))
        self.button_a.setText(_translate("Pong", "P1 Up", None))
        self.button_k.setText(_translate("Pong", "P2 Up", None))
        self.button_r.setText(_translate("Pong", "Restart", None))
        self.label_4.setText(_translate("Pong", "Dual Button", None))
        self.label_13.setText(_translate("Pong", "DB1 Left", None))
        self.label_17.setText(_translate("Pong", "DB1 Right", None))
        self.label_18.setText(_translate("Pong", "DB2 Left", None))
        self.label_19.setText(_translate("Pong", "DB2 Right", None))

